# aqui irei definir o nome do pipeline
name: Meu primeiro WorkFlow  
#Quais eventos (gatilhos) diparam o fluxo?  
#temos eventos do tipo push, pull request, merge, rebase ...
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches:
    - main
    - master
    - develop
#quais são os trabalhos (tarefas) serem executados pelo workflow
jobs:
  tarefa01:
    name: Primeira tarefa
    needs: tarefa03
    runs-on: ubuntu-latest
    steps:
      - name: Passo 1  
        run: echo "Executando o passo 1"
      - name: Passo 2
        run: echo "Executando o passo 2"
      - name: Passo 3  
        run: echo "Executando o passo 3"

  tarefa02:
    name: Segunda tarefa
    needs: tarefa01
    runs-on: ubuntu-latest
    steps:
      - name: Passo 04  
        run: echo "Executando o passo 4"
      - name: Passo 05  
        run: echo "Executando o passo 5"
      - name: Passo 06  
        run: echo "Executando o passo 6"

  tarefa03:
    name: Terceira tarefa
    runs-on: ubuntu-latest
    steps:
      - name: Passo 07  
        run: echo "Executando o passo 7"
      - name: Passo 08  
        run: echo "Executando o passo 8"
      - name: Passo 09  
        run: echo "Executando o passo 9"
